# Hand-written migration (this session, 2026-09-23) -- NOT generated by
# `manage.py makemigrations` (no working shell this session). Adds the
# fare_breakdown field declared on the ServiceRequest model in models.py
# to this app's migration STATE so `makemigrations --check` stops flagging
# it as an undeclared model change.
#
# This is a pure state operation with no real DDL: ServiceRequest here is
# managed=False (db_table='service_requests_servicerequest', owned by the
# Customer app). The physical column already exists -- it was added by
# Customer/backend/service_requests/migrations/
# 0066_servicerequest_fare_breakdown.py against the same shared table.
# Django's schema editor skips AddField for unmanaged models, so applying
# this migration touches no real table; it only makes this app's recorded
# migration state match models.py.
#
# Depends on the merge in 0003 rather than either individual 0002, since
# that's now the single leaf.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_merge_20260923_gt_vehicle_compat'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='fare_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
