# Generated by Django 5.0.14 on 2026-09-24 04:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0004_servicerequest_fare_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACInspectionConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnostic_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("199.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_requests_acinspectionconfiguration",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ACInspectionRateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_requests_acinspectionratecategory",
                "ordering": ["display_order", "id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ACInspectionRateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(default="unit", max_length=50)),
                ("service_type", models.CharField(default="REPAIR", max_length=50)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_requests_acinspectionrateitem",
                "ordering": ["display_order", "id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_name_snapshot",
                    models.CharField(
                        default="AC Inspection & Diagnostic Visit", max_length=255
                    ),
                ),
                (
                    "diagnostic_fee_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("199.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="BOOKED",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_requests_customerinspection",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerInspectionRateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name_snapshot", models.CharField(max_length=200)),
                ("item_name_snapshot", models.CharField(max_length=200)),
                ("description_snapshot", models.TextField(blank=True, default="")),
                (
                    "price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unit_snapshot", models.CharField(default="unit", max_length=50)),
                (
                    "service_type_snapshot",
                    models.CharField(default="REPAIR", max_length=50),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "service_requests_customerinspectionratesnapshot",
                "ordering": ["display_order", "id"],
                "managed": False,
            },
        ),
    ]
