# Generated by Django 5.2.17 on 2026-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_acinspectionconfiguration_acinspectionratecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTWaitingChargePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('free_minutes_per_stop', models.PositiveIntegerField(default=0)),
                ('rate_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_charge_per_booking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_requests_gtwaitingchargepolicy',
                'managed': False,
            },
        ),
    ]
