# Generated by Django 5.2.17 on 2026-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_gtwaitingchargepolicy_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTExtraChargePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('allow_toll', models.BooleanField(default=True)),
                ('allow_parking', models.BooleanField(default=True)),
                ('max_amount_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_total_per_booking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_requests_gtextrachargepolicy',
                'managed': False,
            },
        ),
    ]
