# Generated by Django 5.2.17 on 2026-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0007_gtextrachargepolicy_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTOperationsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_radius_meters', models.PositiveIntegerField(default=250)),
                ('delivery_otp_ttl_minutes', models.PositiveIntegerField(default=30)),
                ('max_otp_attempts', models.PositiveIntegerField(default=5)),
                ('delivery_otp_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_requests_gtoperationsconfig',
                'managed': False,
            },
        ),
    ]
