# Generated by Django 5.0.14 on 2026-09-01 10:48

import django
from django.db import migrations, models


def add_jobtrackingsession_columns_postgres(apps, schema_editor):
    """
    Postgres-only column-add DDL (information_schema-guarded ALTER TABLE).
    manage.py test always runs against sqlite (workforce_core.settings
    IS_TESTING forces this for any 'test' invocation), so this is a genuine
    no-op there -- the SeparateDatabaseAndState.state_operations above
    already keep Django's model state in sync for that case. Production is
    Postgres-only per settings.py's DATABASES config, so this still runs
    for real there.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='geofence_status') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN geofence_status VARCHAR(50) DEFAULT 'OUTSIDE';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='last_event_emitted_at') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN last_event_emitted_at TIMESTAMP WITH TIME ZONE NULL;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='last_event_state_key') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN last_event_state_key VARCHAR(100) DEFAULT '';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='movement_status') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN movement_status VARCHAR(50) DEFAULT 'UNKNOWN';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='prev_captured_at') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN prev_captured_at TIMESTAMP WITH TIME ZONE NULL;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='prev_latitude') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN prev_latitude DOUBLE PRECISION NULL;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workforce_job_tracking_session' AND column_name='prev_longitude') THEN
                ALTER TABLE workforce_job_tracking_session ADD COLUMN prev_longitude DOUBLE PRECISION NULL;
            END IF;
        END $$;
        """
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('employees', '__first__'),
        ('workforce_api', '0017_criteriaterm_vendorcriteria_vendorinvitation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='walletaccount',
            name='wallet_account_type_matches_owner',
        ),
        migrations.RenameIndex(
            model_name='walletaccount',
            new_name='workforce_w_account_bd42a8_idx',
            old_name='workforce_w_account_5f0a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='walletledgerentry',
            new_name='workforce_w_wallet__e067bd_idx',
            old_name='workforce_w_wallet__1e2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='walletledgerentry',
            new_name='workforce_w_job_id_9969a1_idx',
            old_name='workforce_w_job_id_2f9d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='workforce_w_wallet__124c9d_idx',
            old_name='workforce_w_wallet__7a6d5f_idx',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='geofence_status',
                    field=models.CharField(default='OUTSIDE', max_length=50),
                ),
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='last_event_emitted_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='last_event_state_key',
                    field=models.CharField(blank=True, default='', max_length=100),
                ),
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='movement_status',
                    field=models.CharField(default='UNKNOWN', max_length=50),
                ),
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='prev_captured_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='prev_latitude',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='jobtrackingsession',
                    name='prev_longitude',
                    field=models.FloatField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_jobtrackingsession_columns_postgres, noop_reverse
                ),
            ]
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='initiated_by',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('TECHNICIAN', 'Technician')], db_index=True, default='VENDOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorinvitation',
            name='channel',
            field=models.CharField(choices=[('DIRECT_EMAIL', 'Direct Email'), ('MATCHING_RESULT', 'Matching Result'), ('TECHNICIAN_REQUEST', 'Technician Request')], default='DIRECT_EMAIL', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.CheckConstraint(
                **{
                    ('condition' if getattr(django, 'VERSION', (5, 0)) >= (6, 0) else 'check'): models.Q(
                        models.Q(('account_type', 'PROVIDER_HEAD'), ('company__isnull', False), ('employee__isnull', True)),
                        models.Q(('account_type', 'INDIVIDUAL_WORKER'), ('company__isnull', True), ('employee__isnull', False)),
                        _connector='OR',
                    ),
                    'name': 'wallet_account_type_matches_owner',
                }
            ),
        ),
    ]
