# Generated by Django on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


def add_primary_employee_job_index_postgres(apps, schema_editor):
    """
    Postgres-only conditional partial-unique-index creation, guarded on the
    target table already existing (service_requests_employeejob is owned by
    a different app's migration history). manage.py test always runs
    against sqlite (workforce_core.settings IS_TESTING), which has neither
    information_schema.tables in this form nor partial-index syntax
    compatible with this block, so this is a genuine no-op there. Production
    is Postgres-only per settings.py's DATABASES config.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'service_requests_employeejob') THEN
                CREATE UNIQUE INDEX IF NOT EXISTS unique_primary_employee_job_per_sr ON service_requests_employeejob (service_request_id) WHERE is_primary = true;
            END IF;
        END $$;
        """
    )


def drop_primary_employee_job_index_postgres(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'unique_primary_employee_job_per_sr') THEN
                DROP INDEX IF EXISTS unique_primary_employee_job_per_sr;
            END IF;
        END $$;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '__first__'),
        ('workforce_api', '0018_workforceproviderjoinrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceServiceSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='service_requests.service')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='workforce_api.workforceskill')),
            ],
            options={
                'db_table': 'workforce_service_skill_requirement',
                'unique_together': {('service', 'skill')},
            },
        ),
        migrations.RunPython(
            add_primary_employee_job_index_postgres,
            drop_primary_employee_job_index_postgres,
        ),
    ]
