# Generated by Django 5.0.14 on 2026-09-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workforce_api",
            "0032_remove_inventoryitem_unique_inventory_company_service_and_more",
        ),
        ("workforce_api", "0032_workforcedispatchstate"),
    ]

    operations = []
