# Generated by Django 5.0.14 on 2026-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0033_merge_20260923_1250"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpayment",
            name="is_mock",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workforcejoblifecycleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE_JOB_ACCEPTED", "Employee Job Accepted"),
                    ("EMPLOYEE_JOB_CANCELLED", "Employee Job Cancelled"),
                    ("EMPLOYEE_JOB_DECLINED", "Employee Job Declined"),
                    (
                        "EMPLOYEE_JOB_REDISPATCH_STARTED",
                        "Employee Job Redispatch Started",
                    ),
                    ("NEW_EMPLOYEE_ASSIGNED", "New Employee Assigned"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
