# Generated by Django 5.0.14 on 2026-09-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0034_add_workforce_outbound_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletledgerentry",
            name="is_mock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workforcequote",
            name="estimated_duration_days",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
