# Generated by Django 5.0.14 on 2026-09-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_own_employee_tables"),
        (
            "service_requests",
            "0005_acinspectionconfiguration_acinspectionratecategory_and_more",
        ),
        ("workforce_api", "0038_pricing_policy_technician_free_cancel_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsCheckpointVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkpoint",
                    models.CharField(
                        choices=[("PICKUP", "Pickup"), ("DROP", "Drop")], max_length=10
                    ),
                ),
                ("geofence_passed", models.BooleanField(default=False)),
                ("gps_lat", models.FloatField(blank=True, null=True)),
                ("gps_lon", models.FloatField(blank=True, null=True)),
                ("target_lat", models.FloatField(blank=True, null=True)),
                ("target_lon", models.FloatField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                (
                    "geofence_note",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("gps_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof_photo",
                    models.FileField(
                        blank=True, null=True, upload_to="logistics_checkpoints/"
                    ),
                ),
                ("photo_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("otp_code", models.CharField(blank=True, default="", max_length=6)),
                ("otp_generated_at", models.DateTimeField(blank=True, null=True)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_attempts", models.IntegerField(default=0)),
                ("otp_verified", models.BooleanField(default=False)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_checkpoint_verifications",
                        to="employees.employee",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_checkpoint_verifications",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_logistics_checkpoint_verification",
            },
        ),
        migrations.AddConstraint(
            model_name="logisticscheckpointverification",
            constraint=models.UniqueConstraint(
                fields=("job", "checkpoint"), name="uniq_logistics_checkpoint_per_job"
            ),
        ),
    ]
