# Generated by Django 5.0.14 on 2026-09-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0034_add_workforce_outbound_webhook'),
        ('workforce_api', '0045_warehousestaff'),
    ]

    operations = [
    ]
