# Generated by Django 5.0.14 on 2026-09-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0039_logistics_checkpoint_verification"),
        ("workforce_api", "0045_merge_20260925_1157"),
    ]

    operations = []
