# Generated by Django 5.0.14 on 2026-09-25 08:51
# Patched to use SeparateDatabaseAndState with idempotent column check so that
# databases where is_mock was already physically added by migration 0035's
# RunPython guard do not throw "duplicate column name: is_mock".

from django.db import migrations, models


def _ensure_walletledgerentry_is_mock(apps, schema_editor):
    WalletLedgerEntry = apps.get_model("workforce_api", "WalletLedgerEntry")
    table = WalletLedgerEntry._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing = {
            col.name
            for col in connection.introspection.get_table_description(cursor, table)
        }
    if "is_mock" not in existing:
        field = models.BooleanField(default=False)
        field.set_attributes_from_name("is_mock")
        schema_editor.add_field(WalletLedgerEntry, field)


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0046_merge_20260925_1418"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="walletledgerentry",
                    name="is_mock",
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name="workforcequote",
                    name="estimated_duration_days",
                    field=models.IntegerField(blank=True, default=1, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _ensure_walletledgerentry_is_mock,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
