# Generated by Django 5.0.14 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0048_sellerproduct_procurement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerhubcategory',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Category photo image URL or uploaded asset path', max_length=1000),
        ),
    ]
