# Generated by Django 5.0.14 on 2026-09-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0047_walletledgerentry_is_mock_and_more'),
        ('workforce_api', '0049_sellerhubcategory_image_url'),
    ]

    operations = [
    ]
