# Generated by Django 5.0.14 on 2026-09-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('workforce_api', '0050_merge_20260928_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforcejobhold',
            name='hold_start',
        ),
        migrations.AlterField(
            model_name='workforcejobhold',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_job_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workforcejobhold',
            name='reason',
            field=models.CharField(choices=[('WEATHER_DELAY', 'Weather / Rain Delay'), ('CLIENT_REQUEST', 'Client Request'), ('MATERIAL_DELAY', 'Material / Parts Delay'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], db_index=True, default='WEATHER_DELAY', max_length=50),
        ),
        migrations.CreateModel(
            name='WarehouseInboundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(help_text='Units of inventory requested for warehouse storage/intake')),
                ('confirmed_quantity', models.PositiveIntegerField(blank=True, help_text='Units physically scanned and confirmed at warehouse intake (Phase Z)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted - Awaiting Receipt'), ('SHORT_RECEIVED', 'Shortfall Reported - Pending Seller Decision'), ('COMPLETED', 'Completed / Verified'), ('REJECTED_RETURN', 'Shortfall Rejected - Return to Seller'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('seller_note', models.TextField(blank=True, default='', help_text='Note or special handling instructions from seller')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, default='', help_text='Note or rejection reason provided by warehouse staff')),
                ('shortfall_note', models.TextField(blank=True, default='', help_text='Warehouse staff explanation of missing/short units')),
                ('shortfall_reported_at', models.DateTimeField(blank=True, null=True)),
                ('seller_shortfall_decision', models.CharField(blank=True, choices=[('ACCEPT_PARTIAL', 'Accept Partial Batch'), ('REJECT_RETURN', 'Reject & Return Entire Batch')], default='', help_text='Seller decision on shortfall notice: ACCEPT_PARTIAL or REJECT_RETURN', max_length=30)),
                ('seller_shortfall_decided_at', models.DateTimeField(blank=True, null=True)),
                ('seller_shortfall_note', models.TextField(blank=True, default='', help_text='Seller note upon deciding shortfall')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inbound_requests', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='workforce_api.sellerproduct')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_inbound_stock', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inbound_stock', to=settings.AUTH_USER_MODEL)),
                ('seller_shortfall_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_shortfalls', to=settings.AUTH_USER_MODEL)),
                ('shortfall_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_shortfalls', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_requests', to='workforce_api.warehouse')),
            ],
            options={
                'db_table': 'workforce_warehouse_inbound_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInboundRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inbound_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('inbound_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workforce_api.warehouseinboundrequest')),
            ],
            options={
                'db_table': 'workforce_warehouse_inbound_request_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInboundUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(help_text='1-indexed sequence number within the inbound request batch (1 to N)')),
                ('barcode', models.CharField(db_index=True, help_text='Unique per-unit Code128 serial barcode for physical intake verification', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING_SCAN', 'Pending Scan'), ('RECEIVED', 'Received / Verified'), ('NOT_RECEIVED', 'Not Received / Missing'), ('RETURN_PENDING', 'Return Pending to Seller')], db_index=True, default='PENDING_SCAN', max_length=30)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbound_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='workforce_api.warehouseinboundrequest')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_inbound_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workforce_warehouse_inbound_unit',
                'ordering': ['unit_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, help_text='Unique return batch identifier (e.g. RET-INB-0042)', max_length=50, unique=True)),
                ('returned_quantity', models.PositiveIntegerField(help_text='Count of physical units to be returned back to the seller')),
                ('seller_address', models.TextField(help_text='Seller company destination address for returning physical goods')),
                ('seller_city', models.CharField(blank=True, default='', max_length=100)),
                ('seller_phone', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.CharField(default='INBOUND_SHORTFALL_REJECTED', help_text='Reason code for warehouse return', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_DISPATCH', 'Pending Return to Seller'), ('DISPATCHED', 'Dispatched to Seller'), ('RETURNED', 'Returned / Handed Over to Seller'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_DISPATCH', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_portal_returns', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_portal_returns', to=settings.AUTH_USER_MODEL)),
                ('inbound_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_returns', to='workforce_api.warehouseinboundrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_portal_returns', to='workforce_api.sellerproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_portal_returns', to='workforce_api.warehouse')),
            ],
            options={
                'db_table': 'workforce_warehouse_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouseinboundrequest',
            index=models.Index(fields=['company', 'status'], name='wf_wh_inb_comp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinboundrequest',
            index=models.Index(fields=['warehouse', 'status'], name='wf_wh_inb_wh_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinboundrequest',
            index=models.Index(fields=['product', 'status'], name='wf_wh_inb_prod_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinboundunit',
            index=models.Index(fields=['inbound_request', 'status'], name='wf_wh_inb_unit_req_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinboundunit',
            index=models.Index(fields=['barcode'], name='wf_wh_inb_unit_barcode_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouseinboundunit',
            constraint=models.UniqueConstraint(fields=('inbound_request', 'unit_number'), name='unique_inbound_request_unit_number'),
        ),
        migrations.AddIndex(
            model_name='warehousereturn',
            index=models.Index(fields=['warehouse', 'status'], name='wf_wh_ret_wh_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereturn',
            index=models.Index(fields=['company', 'status'], name='wf_wh_ret_comp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereturn',
            index=models.Index(fields=['return_number'], name='wf_wh_ret_num_idx'),
        ),
    ]
