# Generated by Django 5.2.17 on 2026-09-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0053_deliveryslot_deliveryslotbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postserviceproof',
            name='delivery_recipient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='postserviceproof',
            name='delivery_signature',
            field=models.ImageField(blank=True, null=True, upload_to='post_service/signatures/'),
        ),
    ]
