# Generated by Django 5.2.17 on 2026-10-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0054_gt_delivery_signature_recipient'),
        ('workforce_api', '0055_sellerproductspec'),
    ]

    operations = [
    ]
