# Generated by Django 5.0.14 on 2026-10-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0054_gt_delivery_signature_recipient"),
        ("workforce_api", "0055_sellerproductspec"),
    ]

    operations = []
