# Generated by Django 5.0.14 on 2026-10-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0056_merge_20261002_0348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workforcequoteitem",
            name="material_source",
            field=models.CharField(default="SEVO", max_length=50),
        ),
    ]
