# Generated by Django 5.0.14 on 2026-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0056_basket_slot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='fssai_license_number',
            field=models.CharField(blank=True, default='', help_text='Optional product-specific FSSAI license override. If blank, falls back to store-level FSSAI.', max_length=100),
        ),
        migrations.AlterField(
            model_name='workforcequoteitem',
            name='material_source',
            field=models.CharField(default='SEVO', max_length=50),
        ),
    ]
